name: CI

on: 
  push: 
    branches: [main, dev, "**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript check
        run: npx tsc --noEmit

      - name: Lint check
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build
